### PR TITLE
WIP Craft 5 Compat

### PR DESCRIPTION
**Pull request by markhuot**

### CODE REVIEW

**Comment by bencroker** [comment]
@markhuot have you managed to get mocks working?

Any time I try to mock any class, I get an `Interface "MockInterface" not found` error. I still can’t seem to track down why the `MockInterface` class is not found. It’s there and it is being autoloaded, with Mockery 1.6.7 installed.

303925776-cfca252c-fd6a-4b72-b811-1e2954a747b9

**Comment by bencroker** [comment]
Never mind, reinstalling Mockery appears to have solved it.

**Comment by markhuot** [comment]
All tests should be passing now! I'm just going to wrap up/fix the types/PHPstan side of things and then this should be ready to merge. Should support 4.5+ and 5.0+ moving forward now. Dropping support for 3.x

**Comment by bencroker** [comment]
Looks like this is getting close! Just want to make sure that https://github.com/markhuot/craft-pest-core/pull/24 is on your radar, as it is currently a blocking issue when using factory methods.

**Pull request merged**
